Last login: Fri Feb 17 17:23:04 on ttys000
Mallorys-MacBook-Pro:~ Mal$ cd
Mallorys-MacBook-Pro:~ Mal$ ls
AEX1.R			Music			anaconda
Applications		Newton-Raphson.py	hagadorn_references.bib
C-PP_lessonnotes.py	Pictures		r-intro-mahagadorn
DLNode.py		PopulusHelp.pdf		untitled10.py
Desktop			Public			untitled12.py
Documents		R_World			untitled13.py
Downloads		RcmdrMarkdown.Rmd	untitled3.py
Lesson1_mahagadorn	RcmdrMarkdown.html	untitled7.py
Library			RcmdrMarkdown.md
Movies			Users
Mallorys-MacBook-Pro:~ Mal$ cd Documents/
Mallorys-MacBook-Pro:Documents Mal$ ls
AbundbySite.txt				PCASetup_forR_UpdatedCs.csv
Aphodiine ID for Patrick.xlsx		PCASetup_forR_UpdatedCs_csv.csv
Azar_Amanda_CASPA.pdf			PHD
BioManTab.csv				Personal
CV					Poster write-up.docx
DBEcoMan				Programming
DBEcologyManuscript_Transfered		Raw Pooled Data_2013and2015.csv
EvolutionCourse				Raw Pooled Data_2013and2015.xlsx
IBM					Seagate
ListofSpecies.csv			Student Recommendations
Masters Stuff				TotalAbPooled_10102016.csv
OrgConEstimateS_OUTPUT File_Excel.xlsx	TotalAbPooled_10102016.txt
Organic_Multiple_ESR.txt		TotalAbd_AllFactors.xlsx
Mallorys-MacBook-Pro:Documents Mal$ cd cd Programming/
-bash: cd: cd: No such file or directory
Mallorys-MacBook-Pro:Documents Mal$ ls
AbundbySite.txt				PCASetup_forR_UpdatedCs.csv
Aphodiine ID for Patrick.xlsx		PCASetup_forR_UpdatedCs_csv.csv
Azar_Amanda_CASPA.pdf			PHD
BioManTab.csv				Personal
CV					Poster write-up.docx
DBEcoMan				Programming
DBEcologyManuscript_Transfered		Raw Pooled Data_2013and2015.csv
EvolutionCourse				Raw Pooled Data_2013and2015.xlsx
IBM					Seagate
ListofSpecies.csv			Student Recommendations
Masters Stuff				TotalAbPooled_10102016.csv
OrgConEstimateS_OUTPUT File_Excel.xlsx	TotalAbPooled_10102016.txt
Organic_Multiple_ESR.txt		TotalAbd_AllFactors.xlsx
Mallorys-MacBook-Pro:Documents Mal$ ls
AbundbySite.txt				PCASetup_forR_UpdatedCs.csv
Aphodiine ID for Patrick.xlsx		PCASetup_forR_UpdatedCs_csv.csv
Azar_Amanda_CASPA.pdf			PHD
BioManTab.csv				Personal
CV					Poster write-up.docx
DBEcoMan				Programming
DBEcologyManuscript_Transfered		Raw Pooled Data_2013and2015.csv
EvolutionCourse				Raw Pooled Data_2013and2015.xlsx
IBM					Seagate
ListofSpecies.csv			Student Recommendations
Masters Stuff				TotalAbPooled_10102016.csv
OrgConEstimateS_OUTPUT File_Excel.xlsx	TotalAbPooled_10102016.txt
Organic_Multiple_ESR.txt		TotalAbd_AllFactors.xlsx
Mallorys-MacBook-Pro:Documents Mal$ cd
Mallorys-MacBook-Pro:~ Mal$ ..
-bash: ..: command not found
Mallorys-MacBook-Pro:~ Mal$ c ..
-bash: c: command not found
Mallorys-MacBook-Pro:~ Mal$ cd ..
Mallorys-MacBook-Pro:Users Mal$ ls
Mal	Shared
Mallorys-MacBook-Pro:Users Mal$ pwd
/Users
Mallorys-MacBook-Pro:Users Mal$ pwd
/Users
Mallorys-MacBook-Pro:Users Mal$ ls
Mal	Shared
Mallorys-MacBook-Pro:Users Mal$ cd Mal/
Mallorys-MacBook-Pro:~ Mal$ cd Documents/Programming/
Mallorys-MacBook-Pro:Programming Mal$ ls
ProgrammingClass	R Work			Stuff
Mallorys-MacBook-Pro:Programming Mal$ ls
NerdClub		R Work
ProgrammingClass	Stuff
Mallorys-MacBook-Pro:Programming Mal$ cd NerdClub/
Mallorys-MacBook-Pro:NerdClub Mal$ ls
Mallorys-MacBook-Pro:NerdClub Mal$ git clone https://github.com/willpearse/natdb.git
Cloning into 'natdb'...
remote: Counting objects: 38, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 38 (delta 9), reused 38 (delta 9), pack-reused 0
Unpacking objects: 100% (38/38), done.
Mallorys-MacBook-Pro:NerdClub Mal$ ls
Mallorys-MacBook-Pro:NerdClub Mal$ git clone https://github.com/mahagadorn/natdb.git
Cloning into 'natdb'...
remote: Counting objects: 38, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 38 (delta 9), reused 38 (delta 9), pack-reused 0
Unpacking objects: 100% (38/38), done.
Mallorys-MacBook-Pro:NerdClub Mal$ 
Mallorys-MacBook-Pro:NerdClub Mal$ 
Mallorys-MacBook-Pro:NerdClub Mal$ 
Mallorys-MacBook-Pro:NerdClub Mal$ 
Mallorys-MacBook-Pro:NerdClub Mal$ 
Mallorys-MacBook-Pro:NerdClub Mal$ 
Mallorys-MacBook-Pro:NerdClub Mal$ pwd
/Users/Mal/Documents/Programming/NerdClub
Mallorys-MacBook-Pro:NerdClub Mal$ ls
Trait_sheets	natdb
Mallorys-MacBook-Pro:NerdClub Mal$ cd natdb/
Mallorys-MacBook-Pro:natdb Mal$ ls
DESCRIPTION	NAMESPACE	README.md	man
LICENSE		R		inst		vignettes
Mallorys-MacBook-Pro:natdb Mal$ ..
-bash: ..: command not found
Mallorys-MacBook-Pro:natdb Mal$ cd ..
Mallorys-MacBook-Pro:NerdClub Mal$ cd
Mallorys-MacBook-Pro:~ Mal$ ls
AEX1.R			Music			anaconda
Applications		Newton-Raphson.py	hagadorn_references.bib
C-PP_lessonnotes.py	Pictures		r-intro-mahagadorn
DLNode.py		PopulusHelp.pdf		untitled10.py
Desktop			Public			untitled12.py
Documents		R_World			untitled13.py
Downloads		RcmdrMarkdown.Rmd	untitled3.py
Lesson1_mahagadorn	RcmdrMarkdown.html	untitled7.py
Library			RcmdrMarkdown.md
Movies			Users
Mallorys-MacBook-Pro:~ Mal$ cd ~/Documents/Programming
Mallorys-MacBook-Pro:Programming Mal$ ls
NerdClub		R Work
ProgrammingClass	Stuff
Mallorys-MacBook-Pro:Programming Mal$ cd NerdClub/
Mallorys-MacBook-Pro:NerdClub Mal$ ls
Trait_sheets	natdb
Mallorys-MacBook-Pro:NerdClub Mal$ cd Trait_sheets/
Mallorys-MacBook-Pro:Trait_sheets Mal$ ls
es6b00315_si_002.xlsx	~$es6b00315_si_002.xlsx
Mallorys-MacBook-Pro:Trait_sheets Mal$ pwd
/Users/Mal/Documents/Programming/NerdClub/Trait_sheets
Mallorys-MacBook-Pro:Trait_sheets Mal$ ls
es6b00315_si_002.xlsx
Mallorys-MacBook-Pro:Trait_sheets Mal$ ls -a
.			..			es6b00315_si_002.xlsx
Mallorys-MacBook-Pro:Trait_sheets Mal$ touch .barry
Mallorys-MacBook-Pro:Trait_sheets Mal$ ls
es6b00315_si_002.xlsx
Mallorys-MacBook-Pro:Trait_sheets Mal$ ls -a
.			.barry
..			es6b00315_si_002.xlsx
Mallorys-MacBook-Pro:Trait_sheets Mal$ nano .barry 
Mallorys-MacBook-Pro:Trait_sheets Mal$ mv .barry barry
Mallorys-MacBook-Pro:Trait_sheets Mal$ ls
barry			es6b00315_si_002.xlsx
Mallorys-MacBook-Pro:Trait_sheets Mal$ touch .travis.yml
Mallorys-MacBook-Pro:Trait_sheets Mal$ ls
barry			es6b00315_si_002.xlsx
Mallorys-MacBook-Pro:Trait_sheets Mal$ ls -a
.			.travis.yml		es6b00315_si_002.xlsx
..			barry
Mallorys-MacBook-Pro:Trait_sheets Mal$ nano .travis.yml travis.yml

  GNU nano 2.0.6             File: .travis.yml                        Modified  


language: r
cache: packages

r_github_packages: ropensci/testdat   
























^G Get Help  ^O WriteOut  ^R Read File ^Y Prev Page ^K Cut Text  ^C Cur Pos
^X Exit      ^J Justify   ^W Where Is  ^V Next Page ^U UnCut Text^T To Spell
